[platformio]
default_envs = p7_coffre

[env:p7_coffre]
platform  = espressif32@6.5.0
board     = esp32dev
framework = espidf

monitor_speed   = 115200
monitor_filters = esp32_exception_decoder

build_src_filter =
    +<main.c>
    +<../../../lib/espnow_common/espnow_slave.c>

build_flags =
    -I${PROJECT_DIR}/main
    -I${PROJECT_DIR}/../../../lib/espnow_common

# Build: pio run
# Flash:  pio run -t upload -e p7_coffre
# Monitor: pio device monitor
# Note: master must send MSG_PUZZLE_CONFIG with 8-digit code before '#' is accepted
