idf_component_register(
    SRCS
        "main.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        joltwallet__littlefs
        ota_server
        media_manager
        npc_engine
        hints_client
        voice_pipeline
        nvs_flash
        esp_timer
        esp_system
        esp_wifi
        esp_netif
        esp_event
)
